### ISSUE TITLE
HIGHEST/MAXIMUM PRIORITY: CSNAP DATABASE DOES NOT ALWAYS ASSIGN USER INFORMATION TO PROJECTS SAVED ON THE CLOUD

### ISSUE THREAD

**Issue by ibara** [GK-12/Snap--Build-Your-Own-Blocks#41]
Today in Laquana's class I stumbled upon a rather massive bug: CSnap is not always saving author information as part of the save. Those save show up with an author of (none). The students cannot then retrieve the saved files in the future since the cloud site has no idea to whom these projects belong.

Yes, we can manually go back and reassign projects to users. But there's no way we're going to remember every user who made every project.

**Comment by ibara** [comment]
More info:
User was logged in and I was physically at the computer doing the saving.
1. Create project
2. File->Save
3. Click Cloud
4. Name file
5. Click Save
6. File->Open
7. No project??? Let's save it again...
8. Repeat 2-6
9. Project is there. Good.
10. I then log into community site admin panel
11. Projects->All Classes
12. Project appears twice: once with an author of (None) and once with the correct author.
13. I look through other projects and it looks like this bug has bitten many people, including several fellows.
14. Send this ticket.

**Comment by chuck211991** [comment]
Wow; that is a pretty high priority! 

I'm having some trouble reproducing this though. Should step 2 be File->Save As?

(I found some unrelated incorrect behavior though; you should be prompted to name the project if it hasn't been saved before)

**Comment by chuck211991** [comment]
Ok, I reproduced the bug uisng Save As. Wrote a test and fixed it in commit https://github.com/GK-12/rpi_csdt_community/commit/eb8e9bbb70e19e92f1a57cc3a56e688cb44b8b2d
